In [4]:
import pandas as pd

df = pd.read_csv("../data/reviews_badminton/data.csv")
df

,Reviewer Name,Review Title,Place of Review,Up Votes,Down Votes,Month,Review text,Ratings
0,Kamal Suresh,Nice product,"Certified Buyer, Chirakkal",889.0,64.0,Feb 2021,"Nice product, good quality, but price is now r...",4
1,Flipkart Customer,Don't waste your money,"Certified Buyer, Hyderabad",109.0,6.0,Feb 2021,They didn't supplied Yonex Mavis 350. Outside ...,1
2,A. S. Raja Srinivasan,Did not meet expectations,"Certified Buyer, Dharmapuri",42.0,3.0,Apr 2021,Worst product. Damaged shuttlecocks packed in ...,1
3,Suresh Narayanasamy,Fair,"Certified Buyer, Chennai",25.0,1.0,NaN,"Quite O. K. , but nowadays the quality of the...",3
4,ASHIK P A,Over priced,NaN,147.0,24.0,Apr 2016,Over pricedJust â?¹620 ..from retailer.I didn'...,1
...,...,...,...,...,...,...,...,...
8513,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
8514,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
8515,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
8516,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
8517,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4

In [7]:
df.columns = df.columns.str.lower().str.replace(" ", "_")
df.columns

Index(['reviewer_name', 'review_title', 'place_of_review', 'up_votes',
       'down_votes', 'month', 'review_text', 'ratings'],
      dtype='object')

In [5]:
import re
import nltk
from nltk.corpus import stopwords

nltk.download("stopwords")

stop_words = set(stopwords.words("english"))

def clean_text(text):
    text = str(text).lower()                     # lowercase
    text = re.sub(r"[^a-zA-Z ]", "", text)       # remove special chars & numbers
    words = text.split()                         # tokenize
    words = [w for w in words if w not in stop_words]  # remove stopwords
    return " ".join(words)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

In [8]:
df["clean_review"] = df["review_text"].apply(clean_text)
df[["review_text", "clean_review"]].head()

,review_text,clean_review
0,"Nice product, good quality, but price is now r...",nice product good quality price rising bad sig...
1,They didn't supplied Yonex Mavis 350. Outside ...,didnt supplied yonex mavis outside cover yonex...
2,Worst product. Damaged shuttlecocks packed in ...,worst product damaged shuttlecocks packed new ...
3,"Quite O. K. , but nowadays the quality of the...",quite k nowadays quality corks like years back...
4,Over pricedJust â?¹620 ..from retailer.I didn'...,pricedjust retaileri didnt understand wat adva...

In [ ]:
%pip install spacy

Collecting spacy
  Downloading spacy-3.8.11-cp312-cp312-win_amd64.whl.metadata (28 kB)
Collecting spacy-legacy<3.1.0,>=3.0.11 (from spacy)
  Downloading spacy_legacy-3.0.12-py2.py3-none-any.whl.metadata (2.8 kB)
Collecting spacy-loggers<2.0.0,>=1.0.0 (from spacy)
  Downloading spacy_loggers-1.0.5-py3-none-any.whl.metadata (23 kB)
Collecting murmurhash<1.1.0,>=0.28.0 (from spacy)
  Downloading murmurhash-1.0.15-cp312-cp312-win_amd64.whl.metadata (2.3 kB)
Collecting cymem<2.1.0,>=2.0.2 (from spacy)
  Downloading cymem-2.0.13-cp312-cp312-win_amd64.whl.metadata (9.9 kB)
Collecting preshed<3.1.0,>=3.0.2 (from spacy)
  Downloading preshed-3.0.12-cp312-cp312-win_amd64.whl.metadata (2.6 kB)
Collecting thinc<8.4.0,>=8.3.4 (from spacy)
  Downloading thinc-8.3.10-cp312-cp312-win_amd64.whl.metadata (15 kB)
Collecting wasabi<1.2.0,>=0.9.1 (from spacy)
  Downloading wasabi-1.1.3-py3-none-any.whl.metadata (28 kB)
Collecting srsly<3.0.0,>=2.4.3 (from spacy)
  Downloading srsly-2.5.2-cp312-cp312-win_amd64.whl.metadata (20 kB)
Collecting catalogue<2.1.0,>=2.0.6 (from spacy)
  Downloading catalogue-2.0.10-py3-none-any.whl.metadata (14 kB)
Collecting weasel<0.5.0,>=0.4.2 (from spacy)
  Downloading weasel-0.4.3-py3-none-any.whl.metadata (4.6 kB)
Collecting typer-slim<1.0.0,>=0.3.0 (from spacy)
  Downloading typer_slim-0.21.1-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in c:\programdata\anaconda3\lib\site-packages (from spacy) (4.66.5)
Requirement already satisfied: numpy>=1.19.0 in c:\programdata\anaconda3\lib\site-packages (from spacy) (1.26.4)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\programdata\anaconda3\lib\site-packages (from spacy) (2.32.3)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in c:\programdata\anaconda3\lib\site-packages (from spacy) (2.8.2)
Requirement already satisfied: jinja2 in c:\programdata\anaconda3\lib\site-packages (from spacy) (3.1.4)
Requirement already satisfied: setuptools in c:\programdata\anaconda3\lib\site-packages (from spacy) (75.1.0)
Requirement already satisfied: packaging>=20.0 in c:\programdata\anaconda3\lib\site-packages (from spacy) (24.1)
Requirement already satisfied: annotated-types>=0.4.0 in c:\programdata\anaconda3\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.6.0)
Requirement already satisfied: pydantic-core==2.20.1 in c:\programdata\anaconda3\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.20.1)
Requirement already satisfied: typing-extensions>=4.6.1 in c:\programdata\anaconda3\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.14.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2025.8.3)
Collecting blis<1.4.0,>=1.3.0 (from thinc<8.4.0,>=8.3.4->spacy)
  Downloading blis-1.3.3-cp312-cp312-win_amd64.whl.metadata (7.7 kB)
Collecting confection<1.0.0,>=0.0.1 (from thinc<8.4.0,>=8.3.4->spacy)
  Downloading confection-0.1.5-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from tqdm<5.0.0,>=4.38.0->spacy) (0.4.6)
Requirement already satisfied: click>=8.0.0 in c:\programdata\anaconda3\lib\site-packages (from typer-slim<1.0.0,>=0.3.0->spacy) (8.1.7)
Collecting cloudpathlib<1.0.0,>=0.7.0 (from weasel<0.5.0,>=0.4.2->spacy)
  Downloading cloudpathlib-0.23.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in c:\programdata\anaconda3\lib\site-packages (from weasel<0.5.0,>=0.4.2->spacy) (5.2.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\programdata\anaconda3\lib\site-packages (from jinja2->spacy) (2.1.3)
Downloading spacy-3.8.11-cp312-cp312-win_amd64.whl (14.2 MB)
   ---------------------------------------- 0.0/14.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.2 MB ? eta -:--:--
   - -------------------------------------- 0.5/14.2 MB 1.4 MB/s eta 0:00:10
   -- ------------------------------------- 0.8/14.2 MB 1.4 MB/s eta 0:00:10
   -- ------------------------------------- 1.0/14.2 MB 1.3 MB/s eta 0:00:11
   ---- ----------------------------------- 1.6/14.2 MB 1.6 MB/s eta 0:00:08
   ----- ---------------------------------- 1.8/14.2 MB 1.5 MB/s eta 0:00:08
   ----- ---------------------------------- 2.1/14.2 MB 1.6 MB/s eta 0:00:08
   ------- -------------------------------- 2.6/14.2 MB 1.6 MB/s eta 0:00:08
   -------- ------------------------------- 2.9/14.2 MB 1.6 MB/s eta 0:00:08
   -------- ------------------------------- 3.1/14.2 MB 1.6 MB/s eta 0:00:08
   ---------- ----------------------------- 3.7/14.2 MB 1.7 MB/s eta 0:00:07
   ----------- ---------------------------- 3.9/14.2 MB 1.7 MB/s eta 0:00:07
   ----------- ---------------------------- 4.2/14.2 MB 1.7 MB/s eta 0:00:06
   ------------ --------------------------- 4.5/14.2 MB 1.6 MB/s eta 0:00:06
   -------------- ------------------------- 5.0/14.2 MB 1.6 MB/s eta 0:00:06
   -------------- ------------------------- 5.0/14.2 MB 1.6 MB/s eta 0:00:06
   -------------- ------------------------- 5.0/14.2 MB 1.6 MB/s eta 0:00:06
   --------------- ------------------------ 5.5/14.2 MB 1.5 MB/s eta 0:00:06
   ---------------- ----------------------- 6.0/14.2 MB 1.5 MB/s eta 0:00:06
   ----------------- ---------------------- 6.3/14.2 MB 1.5 MB/s eta 0:00:06
   ------------------- -------------------- 6.8/14.2 MB 1.6 MB/s eta 0:00:05
   -------------------- ------------------- 7.3/14.2 MB 1.6 MB/s eta 0:00:05
   ---------------------- ----------------- 7.9/14.2 MB 1.7 MB/s eta 0:00:04
   ---------------------- ----------------- 8.1/14.2 MB 1.7 MB/s eta 0:00:04
   ------------------------ --------------- 8.7/14.2 MB 1.7 MB/s eta 0:00:04
   ------------------------- -------------- 9.2/14.2 MB 1.7 MB/s eta 0:00:03
   -------------------------- ------------- 9.4/14.2 MB 1.7 MB/s eta 0:00:03
   ---------------------------- ----------- 10.0/14.2 MB 1.7 MB/s eta 0:00:03
   ---------------------------- ----------- 10.2/14.2 MB 1.7 MB/s eta 0:00:03
   ------------------------------ --------- 10.7/14.2 MB 1.7 MB/s eta 0:00:03
   ------------------------------- -------- 11.3/14.2 MB 1.7 MB/s eta 0:00:02
   -------------------------------- ------- 11.5/14.2 MB 1.8 MB/s eta 0:00:02
   --------------------------------- ------ 12.1/14.2 MB 1.8 MB/s eta 0:00:02
   ----------------------------------- ---- 12.6/14.2 MB 1.8 MB/s eta 0:00:01
   ------------------------------------ --- 12.8/14.2 MB 1.8 MB/s eta 0:00:01
   ------------------------------------ --- 13.1/14.2 MB 1.8 MB/s eta 0:00:01
   ------------------------------------- -- 13.4/14.2 MB 1.7 MB/s eta 0:00:01
   -------------------------------------- - 13.6/14.2 MB 1.7 MB/s eta 0:00:01
   ---------------------------------------  13.9/14.2 MB 1.7 MB/s eta 0:00:01
   ---------------------------------------- 14.2/14.2 MB 1.7 MB/s eta 0:00:00
Downloading catalogue-2.0.10-py3-none-any.whl (17 kB)
Downloading cymem-2.0.13-cp312-cp312-win_amd64.whl (40 kB)
Downloading murmurhash-1.0.15-cp312-cp312-win_amd64.whl (25 kB)
Downloading preshed-3.0.12-cp312-cp312-win_amd64.whl (118 kB)
Downloading spacy_legacy-3.0.12-py2.py3-none-any.whl (29 kB)
Downloading spacy_loggers-1.0.5-py3-none-any.whl (22 kB)
Downloading srsly-2.5.2-cp312-cp312-win_amd64.whl (654 kB)
   ---------------------------------------- 0.0/654.8 kB ? eta -:--:--
   ---------------- ----------------------- 262.1/654.8 kB ? eta -:--:--
   ---------------------------------------- 654.8/654.8 kB 1.8 MB/s eta 0:00:00
Downloading thinc-8.3.10-cp312-cp312-win_amd64.whl (1.7 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.7 MB ? eta -:--:--
   ------------------ --------------------- 0.8/1.7 MB 2.0 MB/s eta 0:00:01
   ------------------------------ --------- 1.3/1.7 MB 2.0 MB/s eta 0:00:01
   ------------------------------------ --- 1.6/1.7 MB 2.0 MB/s eta 0:00:01
   ---------------------------------------- 1.7/1.7 MB 1.8 MB/s eta 0:00:00
Downloading typer_slim-0.21.1-py3-none-any.whl (47 kB)
Downloading wasabi-1.1.3-py3-none-any.whl (27 kB)
Downloading weasel-0.4.3-py3-none-any.whl (50 kB)
Downloading blis-1.3.3-cp312-cp312-win_amd64.whl (6.2 MB)
   ---------------------------------------- 0.0/6.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/6.2 MB ? eta -:--:--
   ----- ---------------------------------- 0.8/6.2 MB 2.1 MB/s eta 0:00:03
   ------ --------------------------------- 1.0/6.2 MB 1.9 MB/s eta 0:00:03
   ------ --------------------------------- 1.0/6.2 MB 1.9 MB/s eta 0:00:03
   -------- ------------------------------- 1.3/6.2 MB 1.2 MB/s eta 0:00:04
   ----------- ---------------------------- 1.8/6.2 MB 1.5 MB/s eta 0:00:03
   --------------- ------------------------ 2.4/6.2 MB 1.6 MB/s eta 0:00:03
   ---------------- ----------------------- 2.6/6.2 MB 1.7 MB/s eta 0:00:03
   -------------------- ------------------- 3.1/6.2 MB 1.7 MB/s eta 0:00:02
   ----------------------- ---------------- 3.7/6.2 MB 1.8 MB/s eta 0:00:02
   --------------------------- ------------ 4.2/6.2 MB 1.8 MB/s eta 0:00:02
   ------------------------------ --------- 4.7/6.2 MB 1.8 MB/s eta 0:00:01
   -------------------------------- ------- 5.0/6.2 MB 1.8 MB/s eta 0:00:01
   ----------------------------------- ---- 5.5/6.2 MB 1.9 MB/s eta 0:00:01
   -------------------------------------- - 6.0/6.2 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------- 6.2/6.2 MB 1.8 MB/s eta 0:00:00
Downloading cloudpathlib-0.23.0-py3-none-any.whl (62 kB)
Downloading confection-0.1.5-py3-none-any.whl (35 kB)
Installing collected packages: wasabi, spacy-loggers, spacy-legacy, murmurhash, cymem, cloudpathlib, catalogue, blis, typer-slim, srsly, preshed, confection, weasel, thinc, spacy
Successfully installed blis-1.3.3 catalogue-2.0.10 cloudpathlib-0.23.0 confection-0.1.5 cymem-2.0.13 murmurhash-1.0.15 preshed-3.0.12 spacy-3.8.11 spacy-legacy-3.0.12 spacy-loggers-1.0.5 srsly-2.5.2 thinc-8.3.10 typer-slim-0.21.1 wasabi-1.1.3 weasel-0.4.3

In [11]:
!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
      --------------------------------------- 0.3/12.8 MB ? eta -:--:--
     - -------------------------------------- 0.5/12.8 MB 2.1 MB/s eta 0:00:06
     --- ------------------------------------ 1.0/12.8 MB 2.0 MB/s eta 0:00:06
     ---- ----------------------------------- 1.6/12.8 MB 2.1 MB/s eta 0:00:06
     ------ --------------------------------- 2.1/12.8 MB 2.2 MB/s eta 0:00:05
     -------- ------------------------------- 2.6/12.8 MB 2.2 MB/s eta 0:00:05
     --------- ------------------------------ 3.1/12.8 MB 2.3 MB/s eta 0:00:05
     ----------- ---------------------------- 3.7/12.8 MB 2.3 MB/s eta 0:00:04
     ------------- -------------------------- 4.2/12.8 MB 2.3 MB/s eta 0:00:04
     -------------- ------------------------- 4.7/12.8 MB 2.4 MB/s eta 0:00:04
     ---------------- ----------------------- 5.2/12.8 MB 2.4 MB/s eta 0:00:04
     ------------------ --------------------- 5.8/12.8 MB 2.4 MB/s eta 0:00:03
     ------------------- -------------------- 6.3/12.8 MB 2.4 MB/s eta 0:00:03
     --------------------- ------------------ 6.8/12.8 MB 2.4 MB/s eta 0:00:03
     ---------------------- ----------------- 7.3/12.8 MB 2.4 MB/s eta 0:00:03
     ----------------------- ---------------- 7.6/12.8 MB 2.4 MB/s eta 0:00:03
     ------------------------- -------------- 8.1/12.8 MB 2.4 MB/s eta 0:00:02
     --------------------------- ------------ 8.7/12.8 MB 2.3 MB/s eta 0:00:02
     ---------------------------- ----------- 9.2/12.8 MB 2.3 MB/s eta 0:00:02
     ----------------------------- ---------- 9.4/12.8 MB 2.3 MB/s eta 0:00:02
     ------------------------------- -------- 10.0/12.8 MB 2.3 MB/s eta 0:00:02
     -------------------------------- ------- 10.5/12.8 MB 2.3 MB/s eta 0:00:02
     --------------------------------- ------ 10.7/12.8 MB 2.3 MB/s eta 0:00:01
     ----------------------------------- ---- 11.3/12.8 MB 2.3 MB/s eta 0:00:01
     ------------------------------------ --- 11.8/12.8 MB 2.3 MB/s eta 0:00:01
     -------------------------------------- - 12.3/12.8 MB 2.3 MB/s eta 0:00:01
     ---------------------------------------  12.6/12.8 MB 2.3 MB/s eta 0:00:01
     ---------------------------------------- 12.8/12.8 MB 2.2 MB/s eta 0:00:00
Installing collected packages: en-core-web-sm
Successfully installed en-core-web-sm-3.8.0
[+] Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

In [ ]:
nlp = spacy.load("en_core_web_sm") # type: ignore

def lemmatize_text(text):
    doc = nlp(text)
    return " ".join(token.lemma_ for token in doc)

df["normalized_review"] = df["clean_review"].apply(lemmatize_text)
df[["clean_review", "normalized_review"]].head()

,clean_review,normalized_review
0,nice product good quality price rising bad sig...,nice product good quality price rise bad sign ...
1,didnt supplied yonex mavis outside cover yonex...,do not supply yonex mavis outside cover yonex ...
2,worst product damaged shuttlecocks packed new ...,bad product damage shuttlecock pack new box or...
3,quite k nowadays quality corks like years back...,quite k nowadays quality cork like year back u...
4,pricedjust retaileri didnt understand wat adva...,pricedjust retaileri do not understand wat adv...

In [15]:
def create_sentiment(rating):
    if rating >= 4:
        return "positive"
    elif rating <= 2:
        return "negative"
    else:
        return "neutral"

df["sentiment"] = df["ratings"].apply(create_sentiment)

In [16]:
df = df[df["sentiment"] != "neutral"]
df["sentiment"].value_counts()

sentiment
positive    6826
negative    1077
Name: count, dtype: int64

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7903 entries, 0 to 8517
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   reviewer_name      7893 non-null   object
 1   review_title       7893 non-null   object
 2   place_of_review    7857 non-null   object
 3   up_votes           7893 non-null   float64
 4   down_votes         7893 non-null   float64
 5   month              7474 non-null   object
 6   review_text        7895 non-null   object
 7   ratings            7903 non-null   int64
 8   clean_review       7903 non-null   object
 9   normalized_review  7903 non-null   object
 10  sentiment          7903 non-null   object
dtypes: float64(2), int64(1), object(8)
memory usage: 740.9+ KB

In [20]:
df = df.dropna(subset=[
    "review_text",
    "clean_review",
    "normalized_review",
    "sentiment"
])

In [21]:
df = df.dropna()

In [22]:
df

,reviewer_name,review_title,place_of_review,up_votes,down_votes,month,review_text,ratings,clean_review,normalized_review,sentiment
0,Kamal Suresh,Nice product,"Certified Buyer, Chirakkal",889.0,64.0,Feb 2021,"Nice product, good quality, but price is now r...",4,nice product good quality price rising bad sig...,nice product good quality price rise bad sign ...,positive
1,Flipkart Customer,Don't waste your money,"Certified Buyer, Hyderabad",109.0,6.0,Feb 2021,They didn't supplied Yonex Mavis 350. Outside ...,1,didnt supplied yonex mavis outside cover yonex...,do not supply yonex mavis outside cover yonex ...,negative
2,A. S. Raja Srinivasan,Did not meet expectations,"Certified Buyer, Dharmapuri",42.0,3.0,Apr 2021,Worst product. Damaged shuttlecocks packed in ...,1,worst product damaged shuttlecocks packed new ...,bad product damage shuttlecock pack new box or...,negative
5,Baji Sankar,Mind-blowing purchase,"Certified Buyer, Hyderabad",173.0,45.0,Oct 2018,Good quality product. Delivered on time.READ MORE,5,good quality product delivered timeread,good quality product deliver timeread,positive
6,Flipkart Customer,Must buy!,"Certified Buyer, Doom Dooma",403.0,121.0,Jan 2020,BEST PURCHASE It is a good quality and is more...,5,best purchase good quality durable average shu...,good purchase good quality durable average shu...,positive
...,...,...,...,...,...,...,...,...,...,...,...
8495,vishal kumar ashish,Nice,"Certified Buyer, Haridwar",0.0,0.0,Oct 2016,Thanks to the delivery boy ... Service is alwa...,5,thanks delivery boy service always awesomeread,thank delivery boy service always awesomeread,positive
8496,Nitya Nand Rai,Good choice,"Certified Buyer, Raebareli",0.0,0.0,Oct 2016,Over priced even after 50% discount price is m...,1,priced even discount price much higher usual m...,price even discount price much high usual misl...,negative
8497,Tarun Reddy,Awesome,Certified Buyer,0.0,0.0,Oct 2016,Too much priced. It was getting me for Rs. 640...,1,much priced getting rs home town advantage pur...,much price get rs home town advantage purchasi...,negative
8499,Jayachandra,High cost,"Certified Buyer, Mangalore",0.0,0.0,Dec 2015,Hii flipkart customers care..why your delivery...,5,hii flipkart customers carewhy delivery boys b...,hii flipkart customer carewhy delivery boy bri...,positive
8507,vishnu varma,Really Nice,"Certified Buyer, Agartala",0.0,1.0,Sep 2016,Nice delivery speedREAD MORE,5,nice delivery speedread,nice delivery speedread,positive

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7438 entries, 0 to 8507
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   reviewer_name      7438 non-null   object
 1   review_title       7438 non-null   object
 2   place_of_review    7438 non-null   object
 3   up_votes           7438 non-null   float64
 4   down_votes         7438 non-null   float64
 5   month              7438 non-null   object
 6   review_text        7438 non-null   object
 7   ratings            7438 non-null   int64
 8   clean_review       7438 non-null   object
 9   normalized_review  7438 non-null   object
 10  sentiment          7438 non-null   object
dtypes: float64(2), int64(1), object(8)
memory usage: 697.3+ KB

#### NUMERICAL FEATURE EXTRACTION

#### BAG OF WORDS (BoW)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer # type: ignore

bow_vectorizer = CountVectorizer(max_features=5000)

X_bow = bow_vectorizer.fit_transform(df["normalized_review"])

X_bow.shape

(7438, 3077)

#### TF-IDF

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer # type: ignore

tfidf_vectorizer = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1,2)
)

X_tfidf = tfidf_vectorizer.fit_transform(df["normalized_review"])

X_tfidf.shape

(7438, 5000)

#### WORD2VEC (Semantic Meaning)

In [ ]:
from gensim.models import Word2Vec # type: ignore

sentences = df["normalized_review"].apply(lambda x: x.split())

w2v_model = Word2Vec(
    sentences,
    vector_size=100,
    window=5,
    min_count=2,
    workers=4
)

In [27]:
import numpy as np

def review_vector(review):
    words = review.split()
    vectors = [w2v_model.wv[word] for word in words if word in w2v_model.wv]
    return np.mean(vectors, axis=0) if vectors else np.zeros(100)

X_w2v = np.array(df["normalized_review"].apply(review_vector).tolist())

X_w2v.shape

(7438, 100)

### MODELING APPROACH

##### Train First Model (Logistic Regression)

In [30]:
X = X_tfidf        # from your TF-IDF step
y = df["sentiment"]

##### Train-Test Split

In [ ]:
from sklearn.model_selection import train_test_split # type: ignore

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

##### Train Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression # type: ignore

lr_model = LogisticRegression(max_iter=1000)
lr_model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

##### Predictions

In [33]:
y_pred_lr = lr_model.predict(X_test)

#### MODEL EVALUATION (F1-SCORE)

In [ ]:
from sklearn.metrics import classification_report, f1_score # type: ignore

print(classification_report(y_test, y_pred_lr))
print("F1 Score:", f1_score(y_test, y_pred_lr, pos_label="positive"))

              precision    recall  f1-score   support

    negative       0.88      0.47      0.61       195
    positive       0.92      0.99      0.96      1293

    accuracy                           0.92      1488
   macro avg       0.90      0.73      0.78      1488
weighted avg       0.92      0.92      0.91      1488

F1 Score: 0.9562943593574897

#### Train Naive Bayes

In [ ]:
%pip install scikit-learn

from sklearn.naive_bayes import MultinomialNB # type: ignore

nb_model = MultinomialNB()
nb_model.fit(X_train, y_train)

y_pred_nb = nb_model.predict(X_test)

print(classification_report(y_test, y_pred_nb))
print("F1 Score:", f1_score(y_test, y_pred_nb, pos_label="positive"))

              precision    recall  f1-score   support

    negative       0.88      0.38      0.54       195
    positive       0.91      0.99      0.95      1293

    accuracy                           0.91      1488
   macro avg       0.90      0.69      0.74      1488
weighted avg       0.91      0.91      0.90      1488

F1 Score: 0.951780415430267

#### Train SVM (High Accuracy)

In [ ]:
from sklearn.svm import LinearSVC # type: ignore

svm_model = LinearSVC()
svm_model.fit(X_train, y_train)

y_pred_svm = svm_model.predict(X_test)

print(classification_report(y_test, y_pred_svm))
print("F1 Score:", f1_score(y_test, y_pred_svm, pos_label="positive"))

              precision    recall  f1-score   support

    negative       0.83      0.62      0.71       195
    positive       0.94      0.98      0.96      1293

    accuracy                           0.93      1488
   macro avg       0.89      0.80      0.84      1488
weighted avg       0.93      0.93      0.93      1488

F1 Score: 0.9624288425047438

##### Compare Models

In [37]:
model_scores = {
    "Logistic Regression": f1_score(y_test, y_pred_lr, pos_label="positive"),
    "Naive Bayes": f1_score(y_test, y_pred_nb, pos_label="positive"),
    "SVM": f1_score(y_test, y_pred_svm, pos_label="positive")
}

model_scores

{'Logistic Regression': 0.9562943593574897,
 'Naive Bayes': 0.951780415430267,
 'SVM': 0.9624288425047438}

In [38]:
import joblib

# Save trained SVM model
joblib.dump(svm_model, "../models/sentiment_model.pkl")

# Save TF-IDF vectorizer
joblib.dump(tfidf_vectorizer, "../models/tfidf_vectorizer.pkl")

['../models/tfidf_vectorizer.pkl']

In [39]:
# Save trained SVM model
joblib.dump(svm_model, "../models/sentiment_model.pkl")

['../models/sentiment_model.pkl']

In [41]:
import joblib

model = joblib.load("../models/sentiment_model.pkl")
vectorizer = joblib.load("../models/tfidf_vectorizer.pkl")